"""导入旧 SQL 菜谱数据到 GustoBot-v2 PostgreSQL。

MySQL 只作为历史数据来源：脚本解析 data/insert_sample_data.sql，然后写入 v2 的
PostgreSQL 业务表、Text2SQL schema_catalog，并可选生成真实菜谱 KB 文档。
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Sequence


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ENV_FILE = PROJECT_ROOT / ".env"
DEFAULT_SQL_FILE = PROJECT_ROOT / "data" / "insert_sample_data.sql"

TABLE_MAP = {
    "cuisines": "recipe_cuisines",
    "cooking_tools": "recipe_tools",
    "ingredients": "recipe_ingredients_master",
    "recipes": "recipe_records",
    "recipe_steps": "recipe_steps",
    "recipe_ingredients": "recipe_ingredients",
    "step_tools": "recipe_step_tools",
}


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    sql_file = _resolve_project_path(args.sql_file, label="sql-file")
    _load_env_file(_resolve_optional_project_path(args.env_file, label="env-file"))
    _ensure_project_on_path()

    if args.dry_run:
        _print_json(
            {
                "dry_run": True,
                "sql_file": str(sql_file),
                "insert_counts": _count_insert_statements(sql_file),
            }
        )
        return 0

    from app.core.config import settings

    dsn = args.postgres_dsn or settings.text2sql_postgres_dsn or settings.postgres_dsn
    if not dsn:
        raise SystemExit("缺少 PostgreSQL DSN，无法导入真实菜谱数据。")

    psycopg, dict_row = _ensure_postgres_driver()
    sql_text = _strip_line_comments(sql_file.read_text(encoding="utf-8"))
    stats: dict[str, int] = {table: 0 for table in TABLE_MAP.values()}
    variables: dict[str, int] = {}
    last_insert_id: int | None = None

    with psycopg.connect(dsn, row_factory=dict_row) as connection:
        with connection.cursor() as cursor:
            _ensure_schema(cursor)
            if args.reset:
                _reset_real_tables(cursor)
            for statement in _split_sql_statements(sql_text):
                statement = statement.strip()
                if not statement or statement.startswith("--"):
                    continue
                if statement.upper().startswith("INSERT INTO"):
                    table, rows = _parse_insert(statement, variables)
                    if table in TABLE_MAP:
                        last_insert_id = _import_rows(cursor, table, rows, stats)
                    continue
                selected = _try_assign_selected_id(cursor, statement, variables)
                if selected is not None:
                    continue
                variable_name = _parse_last_insert_assignment(statement)
                if variable_name and last_insert_id is not None:
                    variables[variable_name] = last_insert_id

            _sync_text2sql_recipes(cursor)
            _upsert_schema_catalog(cursor)

    kb_ingested = 0
    kb_chunks = 0
    if args.ingest_kb:
        kb_ingested, kb_chunks = _ingest_recipe_kb_documents(dsn, limit=args.kb_limit)

    _print_json(
        {
            "dry_run": False,
            "sql_file": str(sql_file),
            "postgres_dsn_configured": True,
            "stats": stats,
            "schema_catalog_updated": True,
            "kb_ingested_documents": kb_ingested,
            "kb_ingested_chunks": kb_chunks,
            "status": "ok",
        }
    )
    return 0


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Import real recipe data into GustoBot-v2 PostgreSQL.")
    parser.add_argument("--sql-file", default=str(DEFAULT_SQL_FILE))
    parser.add_argument("--env-file", default=str(DEFAULT_ENV_FILE))
    parser.add_argument("--postgres-dsn", default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--reset", action="store_true", help="清空 v2 真实菜谱业务表后重新导入。")
    parser.add_argument("--ingest-kb", action="store_true", help="把真实菜谱同步生成 KB 文档并写入 pgvector。")
    parser.add_argument("--kb-limit", type=int, default=0, help="限制同步到 KB 的菜谱数量，0 表示不限制。")
    return parser.parse_args(argv)


def _ensure_schema(cursor: Any) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS recipe_cuisines (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL UNIQUE,
            cooking_style text,
            typical_tools jsonb NOT NULL DEFAULT '[]'::jsonb,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS recipe_tools (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL UNIQUE,
            type text NOT NULL DEFAULT 'other',
            material text,
            capacity text,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS recipe_ingredients_master (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL UNIQUE,
            category text,
            calories numeric(10,2) NOT NULL DEFAULT 0,
            protein numeric(10,2) NOT NULL DEFAULT 0,
            carbs numeric(10,2) NOT NULL DEFAULT 0,
            fat numeric(10,2) NOT NULL DEFAULT 0,
            storage_method text,
            shelf_life integer NOT NULL DEFAULT 0,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS recipe_records (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name text NOT NULL UNIQUE,
            description text,
            image_url text,
            video_url text,
            total_time integer NOT NULL DEFAULT 0,
            servings integer NOT NULL DEFAULT 4,
            difficulty text NOT NULL DEFAULT 'easy',
            cuisine_id integer REFERENCES recipe_cuisines(id) ON DELETE SET NULL,
            total_calories numeric(10,2) NOT NULL DEFAULT 0,
            total_protein numeric(10,2) NOT NULL DEFAULT 0,
            total_carbs numeric(10,2) NOT NULL DEFAULT 0,
            total_fat numeric(10,2) NOT NULL DEFAULT 0,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS recipe_steps (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            recipe_id integer NOT NULL REFERENCES recipe_records(id) ON DELETE CASCADE,
            step_number integer NOT NULL,
            action text NOT NULL,
            instruction text NOT NULL,
            duration integer NOT NULL DEFAULT 0,
            temperature text,
            tools_used jsonb NOT NULL DEFAULT '[]'::jsonb,
            tips text,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            UNIQUE (recipe_id, step_number)
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS recipe_ingredients (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            recipe_id integer NOT NULL REFERENCES recipe_records(id) ON DELETE CASCADE,
            ingredient_id integer NOT NULL REFERENCES recipe_ingredients_master(id) ON DELETE RESTRICT,
            quantity text NOT NULL,
            unit text,
            prep_method text,
            prep_time integer NOT NULL DEFAULT 0,
            is_main boolean NOT NULL DEFAULT false,
            substitute text,
            adjusted_calories numeric(10,2) NOT NULL DEFAULT 0,
            ingredient_type text NOT NULL DEFAULT 'auxiliary',
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            UNIQUE (recipe_id, ingredient_id, ingredient_type)
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS recipe_step_tools (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            step_id integer NOT NULL REFERENCES recipe_steps(id) ON DELETE CASCADE,
            tool_id integer NOT NULL REFERENCES recipe_tools(id) ON DELETE RESTRICT,
            usage_text text,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            UNIQUE (step_id, tool_id)
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS recipes (
            recipe_id integer PRIMARY KEY,
            name text NOT NULL,
            cuisine text NOT NULL,
            difficulty text NOT NULL,
            cooking_time_minutes integer NOT NULL,
            popularity integer NOT NULL,
            created_year integer NOT NULL,
            metadata jsonb NOT NULL DEFAULT '{}'::jsonb
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_catalog (
            table_name text PRIMARY KEY,
            table_comment text NOT NULL,
            business_meaning text NOT NULL,
            module text NOT NULL,
            columns jsonb NOT NULL,
            metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
            updated_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )


def _reset_real_tables(cursor: Any) -> None:
    cursor.execute(
        """
        TRUNCATE recipe_step_tools,
                 recipe_ingredients,
                 recipe_steps,
                 recipe_records,
                 recipe_ingredients_master,
                 recipe_tools,
                 recipe_cuisines
        RESTART IDENTITY CASCADE
        """
    )


def _import_rows(cursor: Any, source_table: str, rows: list[dict[str, Any]], stats: dict[str, int]) -> int | None:
    last_id: int | None = None
    for row in rows:
        if source_table == "cuisines":
            last_id = _upsert_returning_id(
                cursor,
                """
                INSERT INTO recipe_cuisines (name, cooking_style, typical_tools)
                VALUES (%s, %s, %s::jsonb)
                ON CONFLICT (name) DO UPDATE
                SET cooking_style = EXCLUDED.cooking_style,
                    typical_tools = EXCLUDED.typical_tools,
                    updated_at = now()
                RETURNING id
                """,
                (row["name"], row.get("cooking_style"), _json(row.get("typical_tools") or [])),
            )
        elif source_table == "cooking_tools":
            last_id = _upsert_returning_id(
                cursor,
                """
                INSERT INTO recipe_tools (name, type, material, capacity)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (name) DO UPDATE
                SET type = EXCLUDED.type,
                    material = EXCLUDED.material,
                    capacity = EXCLUDED.capacity,
                    updated_at = now()
                RETURNING id
                """,
                (row["name"], row.get("type") or "other", row.get("material"), row.get("capacity")),
            )
        elif source_table == "ingredients":
            last_id = _upsert_returning_id(
                cursor,
                """
                INSERT INTO recipe_ingredients_master
                    (name, category, calories, protein, carbs, fat, storage_method, shelf_life)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (name) DO UPDATE
                SET category = EXCLUDED.category,
                    calories = EXCLUDED.calories,
                    protein = EXCLUDED.protein,
                    carbs = EXCLUDED.carbs,
                    fat = EXCLUDED.fat,
                    storage_method = EXCLUDED.storage_method,
                    shelf_life = EXCLUDED.shelf_life,
                    updated_at = now()
                RETURNING id
                """,
                (
                    row["name"],
                    row.get("category"),
                    row.get("calories") or 0,
                    row.get("protein") or 0,
                    row.get("carbs") or 0,
                    row.get("fat") or 0,
                    row.get("storage_method"),
                    row.get("shelf_life") or 0,
                ),
            )
        elif source_table == "recipes":
            last_id = _upsert_returning_id(
                cursor,
                """
                INSERT INTO recipe_records
                    (name, description, image_url, video_url, total_time, servings, difficulty,
                     cuisine_id, total_calories, total_protein, total_carbs, total_fat)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (name) DO UPDATE
                SET description = EXCLUDED.description,
                    image_url = EXCLUDED.image_url,
                    video_url = EXCLUDED.video_url,
                    total_time = EXCLUDED.total_time,
                    servings = EXCLUDED.servings,
                    difficulty = EXCLUDED.difficulty,
                    cuisine_id = EXCLUDED.cuisine_id,
                    total_calories = EXCLUDED.total_calories,
                    total_protein = EXCLUDED.total_protein,
                    total_carbs = EXCLUDED.total_carbs,
                    total_fat = EXCLUDED.total_fat,
                    updated_at = now()
                RETURNING id
                """,
                (
                    row["name"],
                    row.get("description"),
                    row.get("image_url"),
                    row.get("video_url"),
                    row.get("total_time") or 0,
                    row.get("servings") or 4,
                    row.get("difficulty") or "easy",
                    row.get("cuisine_id"),
                    row.get("total_calories") or 0,
                    row.get("total_protein") or 0,
                    row.get("total_carbs") or 0,
                    row.get("total_fat") or 0,
                ),
            )
        elif source_table == "recipe_steps":
            last_id = _upsert_returning_id(
                cursor,
                """
                INSERT INTO recipe_steps
                    (recipe_id, step_number, action, instruction, duration, temperature, tools_used, tips)
                VALUES (%s, %s, %s, %s, %s, %s, %s::jsonb, %s)
                ON CONFLICT (recipe_id, step_number) DO UPDATE
                SET action = EXCLUDED.action,
                    instruction = EXCLUDED.instruction,
                    duration = EXCLUDED.duration,
                    temperature = EXCLUDED.temperature,
                    tools_used = EXCLUDED.tools_used,
                    tips = EXCLUDED.tips,
                    updated_at = now()
                RETURNING id
                """,
                (
                    row["recipe_id"],
                    row["step_number"],
                    row["action"],
                    row["instruction"],
                    row.get("duration") or 0,
                    row.get("temperature"),
                    _json(row.get("tools_used") or []),
                    row.get("tips"),
                ),
            )
        elif source_table == "recipe_ingredients":
            last_id = _upsert_returning_id(
                cursor,
                """
                INSERT INTO recipe_ingredients
                    (recipe_id, ingredient_id, quantity, unit, prep_method, prep_time,
                     is_main, substitute, adjusted_calories, ingredient_type)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (recipe_id, ingredient_id, ingredient_type) DO UPDATE
                SET quantity = EXCLUDED.quantity,
                    unit = EXCLUDED.unit,
                    prep_method = EXCLUDED.prep_method,
                    prep_time = EXCLUDED.prep_time,
                    is_main = EXCLUDED.is_main,
                    substitute = EXCLUDED.substitute,
                    adjusted_calories = EXCLUDED.adjusted_calories,
                    updated_at = now()
                RETURNING id
                """,
                (
                    row["recipe_id"],
                    row["ingredient_id"],
                    str(row["quantity"]),
                    row.get("unit"),
                    row.get("prep_method"),
                    row.get("prep_time") or 0,
                    bool(row.get("is_main")),
                    row.get("substitute"),
                    row.get("adjusted_calories") or 0,
                    row.get("ingredient_type") or "auxiliary",
                ),
            )
        elif source_table == "step_tools":
            last_id = _upsert_returning_id(
                cursor,
                """
                INSERT INTO recipe_step_tools (step_id, tool_id, usage_text)
                VALUES (%s, %s, %s)
                ON CONFLICT (step_id, tool_id) DO UPDATE
                SET usage_text = EXCLUDED.usage_text,
                    updated_at = now()
                RETURNING id
                """,
                (row["step_id"], row["tool_id"], row.get("usage")),
            )
        stats[TABLE_MAP[source_table]] += 1
    return last_id


def _sync_text2sql_recipes(cursor: Any) -> None:
    cursor.execute(
        """
        INSERT INTO recipes
            (recipe_id, name, cuisine, difficulty, cooking_time_minutes, popularity, created_year, metadata)
        SELECT r.id,
               r.name,
               COALESCE(c.name, '未分类'),
               CASE r.difficulty
                   WHEN 'easy' THEN '简单'
                   WHEN 'medium' THEN '中等'
                   WHEN 'hard' THEN '困难'
                   ELSE r.difficulty
               END,
               r.total_time,
               GREATEST(50, 100 - ((r.id - 1) % 50)),
               EXTRACT(YEAR FROM r.created_at)::integer,
               jsonb_build_object('source', 'real_recipe_import', 'real_recipe_id', r.id)
        FROM recipe_records r
        LEFT JOIN recipe_cuisines c ON c.id = r.cuisine_id
        ON CONFLICT (recipe_id) DO UPDATE
        SET name = EXCLUDED.name,
            cuisine = EXCLUDED.cuisine,
            difficulty = EXCLUDED.difficulty,
            cooking_time_minutes = EXCLUDED.cooking_time_minutes,
            popularity = EXCLUDED.popularity,
            created_year = EXCLUDED.created_year,
            metadata = EXCLUDED.metadata
        """
    )


def _upsert_schema_catalog(cursor: Any) -> None:
    schemas = [
        _catalog_row(
            "recipes",
            "Text2SQL 兼容菜谱统计表",
            "用于菜谱数量、菜系、耗时、热度、年份趋势等统计查询，数据来自真实 recipe_records。",
            "recipe_analytics",
            [
                ("recipe_id", "integer", "菜谱唯一编号"),
                ("name", "text", "菜谱名称"),
                ("cuisine", "text", "菜系名称"),
                ("difficulty", "text", "制作难度"),
                ("cooking_time_minutes", "integer", "烹饪耗时，单位分钟"),
                ("popularity", "integer", "热度分"),
                ("created_year", "integer", "录入年份"),
            ],
        ),
        _catalog_row("recipe_records", "真实菜谱主表", "保存菜名、描述、耗时、份量、难度、菜系和营养字段。", "recipe_core"),
        _catalog_row("recipe_cuisines", "真实菜系表", "保存菜系名称、烹饪风格和常用工具。", "recipe_core"),
        _catalog_row("recipe_ingredients_master", "真实食材主数据表", "保存食材名称、分类、营养和储存方式。", "recipe_core"),
        _catalog_row("recipe_steps", "真实菜谱步骤表", "保存每道菜的步骤顺序、动作、说明、时长、温度和工具。", "recipe_core"),
        _catalog_row("recipe_ingredients", "真实菜谱食材关系表", "保存菜谱与食材的用量、预处理方式、主辅料和调料关系。", "recipe_core"),
        _catalog_row("recipe_tools", "真实厨具表", "保存厨具名称、类型、材质和容量。", "recipe_core"),
        _catalog_row("recipe_step_tools", "真实步骤厨具关系表", "保存步骤与厨具的使用关系。", "recipe_core"),
    ]
    for row in schemas:
        cursor.execute(
            """
            INSERT INTO schema_catalog
                (table_name, table_comment, business_meaning, module, columns, metadata)
            VALUES (%s, %s, %s, %s, %s::jsonb, %s::jsonb)
            ON CONFLICT (table_name) DO UPDATE
            SET table_comment = EXCLUDED.table_comment,
                business_meaning = EXCLUDED.business_meaning,
                module = EXCLUDED.module,
                columns = EXCLUDED.columns,
                metadata = EXCLUDED.metadata,
                updated_at = now()
            """,
            (
                row["table_name"],
                row["table_comment"],
                row["business_meaning"],
                row["module"],
                _json(row["columns"]),
                _json({"source": "real_recipe_import"}),
            ),
        )


def _catalog_row(
    table_name: str,
    table_comment: str,
    business_meaning: str,
    module: str,
    columns: list[tuple[str, str, str]] | None = None,
) -> dict[str, Any]:
    return {
        "table_name": table_name,
        "table_comment": table_comment,
        "business_meaning": business_meaning,
        "module": module,
        "columns": [
            {"name": name, "data_type": data_type, "comment": comment, "sample_values": []}
            for name, data_type, comment in (columns or [])
        ],
    }


def _ingest_recipe_kb_documents(dsn: str, *, limit: int) -> tuple[int, int]:
    from app.kb.service import get_kb_service

    documents = _load_recipe_documents(dsn, limit=limit)
    service = get_kb_service()
    ingested = 0
    chunks = 0
    for document in documents:
        result = service.ingest_document(**document)
        ingested += 1
        chunks += result.chunk_count
    return ingested, chunks


def _load_recipe_documents(dsn: str, *, limit: int) -> list[dict[str, Any]]:
    psycopg, dict_row = _ensure_postgres_driver()
    with psycopg.connect(dsn, row_factory=dict_row) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT r.id, r.name, r.description, r.total_time, r.servings, r.difficulty,
                       COALESCE(c.name, '未分类') AS cuisine
                FROM recipe_records r
                LEFT JOIN recipe_cuisines c ON c.id = r.cuisine_id
                ORDER BY r.id
                """
            )
            recipes = cursor.fetchall()
            if limit > 0:
                recipes = recipes[:limit]
            documents = []
            for recipe in recipes:
                cursor.execute(
                    """
                    SELECT i.name, ri.quantity, ri.unit, ri.prep_method, ri.ingredient_type, ri.is_main
                    FROM recipe_ingredients ri
                    JOIN recipe_ingredients_master i ON i.id = ri.ingredient_id
                    WHERE ri.recipe_id = %s
                    ORDER BY ri.is_main DESC, ri.ingredient_type, i.name
                    """,
                    (recipe["id"],),
                )
                ingredients = cursor.fetchall()
                cursor.execute(
                    """
                    SELECT step_number, action, instruction, duration, temperature
                    FROM recipe_steps
                    WHERE recipe_id = %s
                    ORDER BY step_number
                    """,
                    (recipe["id"],),
                )
                steps = cursor.fetchall()
                documents.append(_recipe_to_document(recipe, ingredients, steps))
    return documents


def _recipe_to_document(recipe: dict[str, Any], ingredients: list[dict[str, Any]], steps: list[dict[str, Any]]) -> dict[str, Any]:
    ingredient_text = "；".join(
        f"{item['name']} {item['quantity']}{item.get('unit') or ''} {item.get('prep_method') or ''}".strip()
        for item in ingredients
    )
    step_text = "；".join(
        f"第{item['step_number']}步 {item['action']}：{item['instruction']}" for item in steps
    )
    content = (
        f"菜谱名称：{recipe['name']}\n"
        f"菜系：{recipe['cuisine']}\n"
        f"难度：{recipe['difficulty']}；耗时：{recipe['total_time']}分钟；份量：{recipe['servings']}人份\n"
        f"简介：{recipe.get('description') or ''}\n"
        f"食材：{ingredient_text}\n"
        f"步骤：{step_text}"
    )
    return {
        "title": f"真实菜谱：{recipe['name']}",
        "content": content,
        "source_id": f"real-recipe:{recipe['id']}",
        "metadata": {
            "doc_type": "real_recipe",
            "source": "real_recipe_import",
            "recipe_id": recipe["id"],
            "cuisine": recipe["cuisine"],
            "title": f"真实菜谱：{recipe['name']}",
        },
    }


def _parse_insert(statement: str, variables: dict[str, int]) -> tuple[str, list[dict[str, Any]]]:
    statement = statement.strip()
    match = re.match(
        r"INSERT\s+INTO\s+`?([A-Za-z_][A-Za-z0-9_]*)`?\s*\((.*?)\)\s*VALUES\s*(.*)$",
        statement,
        flags=re.IGNORECASE | re.DOTALL,
    )
    if not match:
        raise ValueError(f"无法解析 INSERT 语句：{statement[:120]}")
    table = match.group(1)
    columns = [_clean_identifier(item) for item in _split_top_level(match.group(2))]
    rows = []
    for raw_row in _parse_value_rows(match.group(3)):
        values = [_eval_value(item, variables) for item in _split_top_level(raw_row)]
        rows.append(dict(zip(columns, values)))
    return table, rows


def _split_sql_statements(sql_text: str) -> list[str]:
    statements: list[str] = []
    current: list[str] = []
    in_string = False
    index = 0
    while index < len(sql_text):
        char = sql_text[index]
        if char == "'" and not _is_escaped(sql_text, index):
            in_string = not in_string
        if char == ";" and not in_string:
            statements.append("".join(current))
            current = []
        else:
            current.append(char)
        index += 1
    if current:
        statements.append("".join(current))
    return statements


def _strip_line_comments(sql_text: str) -> str:
    return "\n".join(
        line for line in sql_text.splitlines() if not line.lstrip().startswith("--")
    )


def _parse_value_rows(values_sql: str) -> list[str]:
    rows: list[str] = []
    current: list[str] = []
    depth = 0
    in_string = False
    capturing = False
    for index, char in enumerate(values_sql):
        if char == "'" and not _is_escaped(values_sql, index):
            in_string = not in_string
        if in_string:
            if capturing:
                current.append(char)
            continue
        if char == "(":
            if depth == 0:
                capturing = True
                current = []
            else:
                current.append(char)
            depth += 1
            continue
        if char == ")":
            depth -= 1
            if depth == 0:
                rows.append("".join(current))
                capturing = False
            elif capturing:
                current.append(char)
            continue
        if capturing:
            current.append(char)
    return rows


def _split_top_level(text: str) -> list[str]:
    parts: list[str] = []
    current: list[str] = []
    depth = 0
    in_string = False
    for index, char in enumerate(text):
        if char == "'" and not _is_escaped(text, index):
            in_string = not in_string
        if not in_string:
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
            elif char == "," and depth == 0:
                parts.append("".join(current).strip())
                current = []
                continue
        current.append(char)
    if current:
        parts.append("".join(current).strip())
    return parts


def _eval_value(token: str, variables: dict[str, int]) -> Any:
    token = token.strip()
    upper = token.upper()
    if upper == "NULL":
        return None
    if token.startswith("@"):
        return variables[token[1:]]
    if upper.startswith("JSON_ARRAY(") and token.endswith(")"):
        inner = token[token.find("(") + 1 : -1]
        return [_eval_value(part, variables) for part in _split_top_level(inner)]
    if token.startswith("'") and token.endswith("'"):
        return token[1:-1].replace("\\'", "'").replace("''", "'")
    if re.fullmatch(r"-?\d+", token):
        return int(token)
    if re.fullmatch(r"-?\d+\.\d+", token):
        return float(token)
    return token


def _try_assign_selected_id(cursor: Any, statement: str, variables: dict[str, int]) -> str | None:
    match = re.match(
        r"SELECT\s+id\s+INTO\s+@([A-Za-z0-9_]+)\s+FROM\s+`?([A-Za-z_][A-Za-z0-9_]*)`?\s+WHERE\s+name\s*=\s*'([^']+)'",
        statement,
        flags=re.IGNORECASE | re.DOTALL,
    )
    if not match:
        return None
    variable, source_table, name = match.groups()
    target_table = TABLE_MAP.get(source_table, source_table)
    cursor.execute(f"SELECT id FROM {target_table} WHERE name = %s", (name,))
    row = cursor.fetchone()
    if row is None:
        raise RuntimeError(f"无法为变量 @{variable} 找到 {source_table}.name={name} 的 id。")
    variables[variable] = int(row["id"])
    return variable


def _parse_last_insert_assignment(statement: str) -> str | None:
    match = re.match(r"SET\s+@([A-Za-z0-9_]+)\s*:=\s*LAST_INSERT_ID\(\)", statement, flags=re.IGNORECASE)
    return match.group(1) if match else None


def _upsert_returning_id(cursor: Any, sql: str, params: tuple[Any, ...]) -> int:
    cursor.execute(sql, params)
    row = cursor.fetchone()
    return int(row["id"])


def _clean_identifier(value: str) -> str:
    return value.strip().strip("`")


def _json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _is_escaped(text: str, index: int) -> bool:
    slash_count = 0
    cursor = index - 1
    while cursor >= 0 and text[cursor] == "\\":
        slash_count += 1
        cursor -= 1
    return slash_count % 2 == 1


def _count_insert_statements(path: Path) -> dict[str, int]:
    counts: dict[str, int] = {}
    for statement in _split_sql_statements(_strip_line_comments(path.read_text(encoding="utf-8"))):
        match = re.match(
            r"\s*INSERT\s+INTO\s+`?([A-Za-z_][A-Za-z0-9_]*)`?.*?\)\s*VALUES\s*(.*)$",
            statement,
            flags=re.IGNORECASE | re.DOTALL,
        )
        if match:
            counts[match.group(1)] = counts.get(match.group(1), 0) + len(_parse_value_rows(match.group(2)))
    return counts


def _resolve_project_path(path_value: str, *, label: str) -> Path:
    path = Path(path_value)
    if not path.is_absolute():
        path = PROJECT_ROOT / path
    resolved = path.resolve()
    try:
        resolved.relative_to(PROJECT_ROOT)
    except ValueError as exc:
        raise SystemExit(f"{label} 必须位于 GustoBot-v2 项目目录内：{resolved}") from exc
    return resolved


def _resolve_optional_project_path(path_value: str, *, label: str) -> Path | None:
    resolved = _resolve_project_path(path_value, label=label)
    return resolved if resolved.exists() else None


def _load_env_file(path: Path | None) -> None:
    if path is None:
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def _ensure_project_on_path() -> None:
    root = str(PROJECT_ROOT)
    if root not in sys.path:
        sys.path.insert(0, root)


def _ensure_postgres_driver():
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:
        raise RuntimeError("当前环境缺少 psycopg，无法导入 PostgreSQL。") from exc
    return psycopg, dict_row


def _print_json(payload: dict[str, Any]) -> None:
    print(json.dumps(payload, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    raise SystemExit(main())
